spring.application.name=flight-reservation-backend
app.cors.allowed-origins=http://localhost:5173
spring.datasource.url=jdbc:postgresql://localhost:5432/flightreservation
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.ai.openai.api-key=${OPENAI_API_KEY}
